const sampleVideos = [
    {
      videoId: "video01",
      title: "Learn React in 30 Minutes",
      thumbnailUrl: "https://i.ytimg.com/vi/Dorf8i6lCuk/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-5s.mp4",
      channelName: "React Mastery",
      views: 15200,
      category: "React",
    },
    {
      videoId: "video02",
      title: "Node.js Crash Course",
      thumbnailUrl: "https://i.ytimg.com/vi/fBNz5xF-Kx4/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-10s.mp4",
      channelName: "Code Academy",
      views: 25000,
      category: "Node.js",
    },
    {
      videoId: "video03",
      title: "JavaScript Full Course for Beginners",
      thumbnailUrl: "https://i.ytimg.com/vi/PkZNo7MFNFg/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-15s.mp4",
      channelName: "Web Dev Simplified",
      views: 105000,
      category: "JavaScript",
    },
    {
      videoId: "video04",
      title: "Python Programming Tutorial",
      thumbnailUrl: "https://i.ytimg.com/vi/rfscVS0vtbw/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-20s.mp4",
      channelName: "Python Hub",
      views: 89000,
      category: "Python",
    },
    {
      videoId: "video05",
      title: "CSS Flexbox & Grid in 20 Minutes",
      thumbnailUrl: "https://i.ytimg.com/vi/1Rs2ND1ryYc/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-30s.mp4",
      channelName: "Design Academy",
      views: 64000,
      category: "CSS",
    },
    {
      videoId: "video06",
      title: "MongoDB Explained for Beginners",
      thumbnailUrl: "https://i.ytimg.com/vi/WwwD1T1kK5I/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-40s.mp4",
      channelName: "Database Experts",
      views: 32000,
      category: "MongoDB",
    },
    {
      videoId: "video07",
      title: "Express.js REST API Tutorial",
      thumbnailUrl: "https://i.ytimg.com/vi/pKd0Rpw7O48/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-45s.mp4",
      channelName: "Backend Pro",
      views: 47000,
      category: "Express.js",
    },
    {
      videoId: "video08",
      title: "Tailwind CSS Crash Course",
      thumbnailUrl: "https://i.ytimg.com/vi/dFgzHOX84xQ/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-50s.mp4",
      channelName: "Design With Code",
      views: 55000,
      category: "CSS",
    },
    {
      videoId: "video09",
      title: "Mastering Redux for React Apps",
      thumbnailUrl: "https://i.ytimg.com/vi/poQXNp9ItL4/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-60s.mp4",
      channelName: "React State Management",
      views: 39000,
      category: "Redux",
    },
    {
      videoId: "video10",
      title: "GraphQL vs REST API",
      thumbnailUrl: "https://i.ytimg.com/vi/ed8SzALpx1Q/maxresdefault.jpg",
      videoUrl: "https://samplelib.com/lib/preview/mp4/sample-70s.mp4",
      channelName: "API Development",
      views: 45000,
      category: "GraphQL",
    },
  ];
  
  export default sampleVideos;
  